name: "Terraform"

on:
  pull_request:
    branches:
      - master

env:
  TF_VERSION: 1.9.5
  ARM_SUBSCRIPTION_ID: b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb

jobs:
  terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: hmcts/cnp-azuredevops-libraries
          path: cnp-azuredevops-libraries

      - name: Setup Script
        run: |
          chmod +x cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh

      - name: Setup Terraform
        run: ./cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
        working-directory: ./
        shell: bash

      - name: Terraform Init
        run: terraform init
        working-directory: example

      - name: Terraform validate
        run: terraform validate
        working-directory: example

      - name: Terraform format
        run: terraform fmt -check
